################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/aes.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/aesni.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/asn1parse.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/base64.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/bignum.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/cipher.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/cipher_wrap.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/ctr_drbg.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/debug.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/ecdh.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/ecp.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/ecp_curves.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/entropy.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/gcm.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/md.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/md_wrap.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/oid.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/pem.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/pk.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/pk_wrap.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/pkparse.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/platform.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/rsa.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/sha1.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/sha256.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/sha512.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/ssl_ciphersuites.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/ssl_cli.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/ssl_tls.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/x509.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/x509_crl.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/x509_crt.c 

OBJS += \
./Middlewares/mbedTLS/aes.o \
./Middlewares/mbedTLS/aesni.o \
./Middlewares/mbedTLS/asn1parse.o \
./Middlewares/mbedTLS/base64.o \
./Middlewares/mbedTLS/bignum.o \
./Middlewares/mbedTLS/cipher.o \
./Middlewares/mbedTLS/cipher_wrap.o \
./Middlewares/mbedTLS/ctr_drbg.o \
./Middlewares/mbedTLS/debug.o \
./Middlewares/mbedTLS/ecdh.o \
./Middlewares/mbedTLS/ecp.o \
./Middlewares/mbedTLS/ecp_curves.o \
./Middlewares/mbedTLS/entropy.o \
./Middlewares/mbedTLS/gcm.o \
./Middlewares/mbedTLS/md.o \
./Middlewares/mbedTLS/md_wrap.o \
./Middlewares/mbedTLS/oid.o \
./Middlewares/mbedTLS/pem.o \
./Middlewares/mbedTLS/pk.o \
./Middlewares/mbedTLS/pk_wrap.o \
./Middlewares/mbedTLS/pkparse.o \
./Middlewares/mbedTLS/platform.o \
./Middlewares/mbedTLS/rsa.o \
./Middlewares/mbedTLS/sha1.o \
./Middlewares/mbedTLS/sha256.o \
./Middlewares/mbedTLS/sha512.o \
./Middlewares/mbedTLS/ssl_ciphersuites.o \
./Middlewares/mbedTLS/ssl_cli.o \
./Middlewares/mbedTLS/ssl_tls.o \
./Middlewares/mbedTLS/x509.o \
./Middlewares/mbedTLS/x509_crl.o \
./Middlewares/mbedTLS/x509_crt.o 

C_DEPS += \
./Middlewares/mbedTLS/aes.d \
./Middlewares/mbedTLS/aesni.d \
./Middlewares/mbedTLS/asn1parse.d \
./Middlewares/mbedTLS/base64.d \
./Middlewares/mbedTLS/bignum.d \
./Middlewares/mbedTLS/cipher.d \
./Middlewares/mbedTLS/cipher_wrap.d \
./Middlewares/mbedTLS/ctr_drbg.d \
./Middlewares/mbedTLS/debug.d \
./Middlewares/mbedTLS/ecdh.d \
./Middlewares/mbedTLS/ecp.d \
./Middlewares/mbedTLS/ecp_curves.d \
./Middlewares/mbedTLS/entropy.d \
./Middlewares/mbedTLS/gcm.d \
./Middlewares/mbedTLS/md.d \
./Middlewares/mbedTLS/md_wrap.d \
./Middlewares/mbedTLS/oid.d \
./Middlewares/mbedTLS/pem.d \
./Middlewares/mbedTLS/pk.d \
./Middlewares/mbedTLS/pk_wrap.d \
./Middlewares/mbedTLS/pkparse.d \
./Middlewares/mbedTLS/platform.d \
./Middlewares/mbedTLS/rsa.d \
./Middlewares/mbedTLS/sha1.d \
./Middlewares/mbedTLS/sha256.d \
./Middlewares/mbedTLS/sha512.d \
./Middlewares/mbedTLS/ssl_ciphersuites.d \
./Middlewares/mbedTLS/ssl_cli.d \
./Middlewares/mbedTLS/ssl_tls.d \
./Middlewares/mbedTLS/x509.d \
./Middlewares/mbedTLS/x509_crl.d \
./Middlewares/mbedTLS/x509_crt.d 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/mbedTLS/aes.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/aes.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/mbedTLS/aes.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/mbedTLS/aesni.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/aesni.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/mbedTLS/aesni.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/mbedTLS/asn1parse.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/asn1parse.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/mbedTLS/asn1parse.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/mbedTLS/base64.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/base64.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/mbedTLS/base64.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/mbedTLS/bignum.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/bignum.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/mbedTLS/bignum.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/mbedTLS/cipher.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/cipher.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/mbedTLS/cipher.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/mbedTLS/cipher_wrap.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/cipher_wrap.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/mbedTLS/cipher_wrap.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/mbedTLS/ctr_drbg.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/ctr_drbg.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/mbedTLS/ctr_drbg.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/mbedTLS/debug.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/debug.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/mbedTLS/debug.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/mbedTLS/ecdh.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/ecdh.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/mbedTLS/ecdh.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/mbedTLS/ecp.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/ecp.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/mbedTLS/ecp.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/mbedTLS/ecp_curves.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/ecp_curves.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/mbedTLS/ecp_curves.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/mbedTLS/entropy.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/entropy.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/mbedTLS/entropy.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/mbedTLS/gcm.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/gcm.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/mbedTLS/gcm.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/mbedTLS/md.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/md.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/mbedTLS/md.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/mbedTLS/md_wrap.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/md_wrap.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/mbedTLS/md_wrap.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/mbedTLS/oid.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/oid.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/mbedTLS/oid.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/mbedTLS/pem.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/pem.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/mbedTLS/pem.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/mbedTLS/pk.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/pk.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/mbedTLS/pk.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/mbedTLS/pk_wrap.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/pk_wrap.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/mbedTLS/pk_wrap.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/mbedTLS/pkparse.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/pkparse.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/mbedTLS/pkparse.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/mbedTLS/platform.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/platform.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/mbedTLS/platform.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/mbedTLS/rsa.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/rsa.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/mbedTLS/rsa.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/mbedTLS/sha1.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/sha1.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/mbedTLS/sha1.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/mbedTLS/sha256.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/sha256.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/mbedTLS/sha256.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/mbedTLS/sha512.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/sha512.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/mbedTLS/sha512.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/mbedTLS/ssl_ciphersuites.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/ssl_ciphersuites.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/mbedTLS/ssl_ciphersuites.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/mbedTLS/ssl_cli.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/ssl_cli.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/mbedTLS/ssl_cli.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/mbedTLS/ssl_tls.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/ssl_tls.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/mbedTLS/ssl_tls.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/mbedTLS/x509.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/x509.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/mbedTLS/x509.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/mbedTLS/x509_crl.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/x509_crl.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/mbedTLS/x509_crl.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/mbedTLS/x509_crt.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/mbedtls/library/x509_crt.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/mbedTLS/x509_crt.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

