################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/src/agenttypesystem.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/src/buffer.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/src/codefirst.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/src/commanddecoder.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/src/constbuffer.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/src/constmap.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/src/crt_abstractions.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/src/datamarshaller.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/src/datapublisher.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/src/doublylinkedlist.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/src/hmac.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/src/hmacsha256.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/src/iotdevice.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/src/iothub_client_authorization.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/src/iothub_client_diagnostic.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/src/iothub_client_ll.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/src/iothub_client_retry_control.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/src/iothub_message.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/src/iothubtransport_mqtt_common.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/src/iothubtransportmqtt.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/src/jsondecoder.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/src/jsonencoder.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/src/map.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/src/methodreturn.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/src/mqtt_client.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/src/mqtt_codec.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/src/mqtt_message.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/src/multitree.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/src/optionhandler.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/parson/parson.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/src/sastoken.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/src/schema.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/src/schemalib.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/src/sha224.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/src/sha384-512.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/src/singlylinkedlist.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/src/string_tokenizer.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/src/strings.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/src/urlencode.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/src/usha.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/src/vector.c \
C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/src/xio.c 

OBJS += \
./Middlewares/AzureIOT/agenttypesystem.o \
./Middlewares/AzureIOT/buffer.o \
./Middlewares/AzureIOT/codefirst.o \
./Middlewares/AzureIOT/commanddecoder.o \
./Middlewares/AzureIOT/constbuffer.o \
./Middlewares/AzureIOT/constmap.o \
./Middlewares/AzureIOT/crt_abstractions.o \
./Middlewares/AzureIOT/datamarshaller.o \
./Middlewares/AzureIOT/datapublisher.o \
./Middlewares/AzureIOT/doublylinkedlist.o \
./Middlewares/AzureIOT/hmac.o \
./Middlewares/AzureIOT/hmacsha256.o \
./Middlewares/AzureIOT/iotdevice.o \
./Middlewares/AzureIOT/iothub_client_authorization.o \
./Middlewares/AzureIOT/iothub_client_diagnostic.o \
./Middlewares/AzureIOT/iothub_client_ll.o \
./Middlewares/AzureIOT/iothub_client_retry_control.o \
./Middlewares/AzureIOT/iothub_message.o \
./Middlewares/AzureIOT/iothubtransport_mqtt_common.o \
./Middlewares/AzureIOT/iothubtransportmqtt.o \
./Middlewares/AzureIOT/jsondecoder.o \
./Middlewares/AzureIOT/jsonencoder.o \
./Middlewares/AzureIOT/map.o \
./Middlewares/AzureIOT/methodreturn.o \
./Middlewares/AzureIOT/mqtt_client.o \
./Middlewares/AzureIOT/mqtt_codec.o \
./Middlewares/AzureIOT/mqtt_message.o \
./Middlewares/AzureIOT/multitree.o \
./Middlewares/AzureIOT/optionhandler.o \
./Middlewares/AzureIOT/parson.o \
./Middlewares/AzureIOT/sastoken.o \
./Middlewares/AzureIOT/schema.o \
./Middlewares/AzureIOT/schemalib.o \
./Middlewares/AzureIOT/sha224.o \
./Middlewares/AzureIOT/sha384-512.o \
./Middlewares/AzureIOT/singlylinkedlist.o \
./Middlewares/AzureIOT/string_tokenizer.o \
./Middlewares/AzureIOT/strings.o \
./Middlewares/AzureIOT/urlencode.o \
./Middlewares/AzureIOT/usha.o \
./Middlewares/AzureIOT/vector.o \
./Middlewares/AzureIOT/xio.o 

C_DEPS += \
./Middlewares/AzureIOT/agenttypesystem.d \
./Middlewares/AzureIOT/buffer.d \
./Middlewares/AzureIOT/codefirst.d \
./Middlewares/AzureIOT/commanddecoder.d \
./Middlewares/AzureIOT/constbuffer.d \
./Middlewares/AzureIOT/constmap.d \
./Middlewares/AzureIOT/crt_abstractions.d \
./Middlewares/AzureIOT/datamarshaller.d \
./Middlewares/AzureIOT/datapublisher.d \
./Middlewares/AzureIOT/doublylinkedlist.d \
./Middlewares/AzureIOT/hmac.d \
./Middlewares/AzureIOT/hmacsha256.d \
./Middlewares/AzureIOT/iotdevice.d \
./Middlewares/AzureIOT/iothub_client_authorization.d \
./Middlewares/AzureIOT/iothub_client_diagnostic.d \
./Middlewares/AzureIOT/iothub_client_ll.d \
./Middlewares/AzureIOT/iothub_client_retry_control.d \
./Middlewares/AzureIOT/iothub_message.d \
./Middlewares/AzureIOT/iothubtransport_mqtt_common.d \
./Middlewares/AzureIOT/iothubtransportmqtt.d \
./Middlewares/AzureIOT/jsondecoder.d \
./Middlewares/AzureIOT/jsonencoder.d \
./Middlewares/AzureIOT/map.d \
./Middlewares/AzureIOT/methodreturn.d \
./Middlewares/AzureIOT/mqtt_client.d \
./Middlewares/AzureIOT/mqtt_codec.d \
./Middlewares/AzureIOT/mqtt_message.d \
./Middlewares/AzureIOT/multitree.d \
./Middlewares/AzureIOT/optionhandler.d \
./Middlewares/AzureIOT/parson.d \
./Middlewares/AzureIOT/sastoken.d \
./Middlewares/AzureIOT/schema.d \
./Middlewares/AzureIOT/schemalib.d \
./Middlewares/AzureIOT/sha224.d \
./Middlewares/AzureIOT/sha384-512.d \
./Middlewares/AzureIOT/singlylinkedlist.d \
./Middlewares/AzureIOT/string_tokenizer.d \
./Middlewares/AzureIOT/strings.d \
./Middlewares/AzureIOT/urlencode.d \
./Middlewares/AzureIOT/usha.d \
./Middlewares/AzureIOT/vector.d \
./Middlewares/AzureIOT/xio.d 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/AzureIOT/agenttypesystem.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/src/agenttypesystem.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/AzureIOT/agenttypesystem.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/AzureIOT/buffer.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/src/buffer.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/AzureIOT/buffer.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/AzureIOT/codefirst.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/src/codefirst.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/AzureIOT/codefirst.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/AzureIOT/commanddecoder.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/src/commanddecoder.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/AzureIOT/commanddecoder.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/AzureIOT/constbuffer.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/src/constbuffer.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/AzureIOT/constbuffer.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/AzureIOT/constmap.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/src/constmap.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/AzureIOT/constmap.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/AzureIOT/crt_abstractions.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/src/crt_abstractions.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/AzureIOT/crt_abstractions.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/AzureIOT/datamarshaller.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/src/datamarshaller.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/AzureIOT/datamarshaller.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/AzureIOT/datapublisher.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/src/datapublisher.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/AzureIOT/datapublisher.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/AzureIOT/doublylinkedlist.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/src/doublylinkedlist.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/AzureIOT/doublylinkedlist.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/AzureIOT/hmac.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/src/hmac.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/AzureIOT/hmac.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/AzureIOT/hmacsha256.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/src/hmacsha256.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/AzureIOT/hmacsha256.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/AzureIOT/iotdevice.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/src/iotdevice.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/AzureIOT/iotdevice.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/AzureIOT/iothub_client_authorization.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/src/iothub_client_authorization.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/AzureIOT/iothub_client_authorization.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/AzureIOT/iothub_client_diagnostic.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/src/iothub_client_diagnostic.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/AzureIOT/iothub_client_diagnostic.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/AzureIOT/iothub_client_ll.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/src/iothub_client_ll.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/AzureIOT/iothub_client_ll.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/AzureIOT/iothub_client_retry_control.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/src/iothub_client_retry_control.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/AzureIOT/iothub_client_retry_control.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/AzureIOT/iothub_message.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/src/iothub_message.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/AzureIOT/iothub_message.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/AzureIOT/iothubtransport_mqtt_common.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/src/iothubtransport_mqtt_common.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/AzureIOT/iothubtransport_mqtt_common.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/AzureIOT/iothubtransportmqtt.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/src/iothubtransportmqtt.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/AzureIOT/iothubtransportmqtt.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/AzureIOT/jsondecoder.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/src/jsondecoder.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/AzureIOT/jsondecoder.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/AzureIOT/jsonencoder.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/src/jsonencoder.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/AzureIOT/jsonencoder.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/AzureIOT/map.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/src/map.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/AzureIOT/map.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/AzureIOT/methodreturn.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/src/methodreturn.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/AzureIOT/methodreturn.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/AzureIOT/mqtt_client.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/src/mqtt_client.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/AzureIOT/mqtt_client.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/AzureIOT/mqtt_codec.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/src/mqtt_codec.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/AzureIOT/mqtt_codec.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/AzureIOT/mqtt_message.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/src/mqtt_message.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/AzureIOT/mqtt_message.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/AzureIOT/multitree.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/src/multitree.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/AzureIOT/multitree.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/AzureIOT/optionhandler.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/src/optionhandler.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/AzureIOT/optionhandler.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/AzureIOT/parson.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/parson/parson.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/AzureIOT/parson.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/AzureIOT/sastoken.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/src/sastoken.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/AzureIOT/sastoken.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/AzureIOT/schema.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/src/schema.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/AzureIOT/schema.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/AzureIOT/schemalib.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/src/schemalib.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/AzureIOT/schemalib.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/AzureIOT/sha224.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/src/sha224.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/AzureIOT/sha224.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/AzureIOT/sha384-512.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/src/sha384-512.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/AzureIOT/sha384-512.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/AzureIOT/singlylinkedlist.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/src/singlylinkedlist.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/AzureIOT/singlylinkedlist.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/AzureIOT/string_tokenizer.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/src/string_tokenizer.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/AzureIOT/string_tokenizer.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/AzureIOT/strings.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/src/strings.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/AzureIOT/strings.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/AzureIOT/urlencode.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/src/urlencode.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/AzureIOT/urlencode.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/AzureIOT/usha.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/src/usha.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/AzureIOT/usha.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/AzureIOT/vector.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/src/vector.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/AzureIOT/vector.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/AzureIOT/xio.o: C:/Users/jamha/Downloads/en.fp-cld-azure1/STM32CubeFunctionPack_AZURE1_V3.3.2/Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/src/xio.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=c99 -DSTM32L475xx -DUSE_HAL_DRIVER -DUSE_STM32L475E_IOT01 '-DNO_LOGGING=1' '-DEINVAL=-1' '-DENOMEM=EINVAL' '-DUSE_GENERICACCESSKEY_IOTHUB=0' '-DREFCOUNT_ATOMIC_DONTCARE=1' '-DDONT_USE_UPLOADTOBLOB=1' -DUSE_MBED_TLS -DUSE_WIFI '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -c -I../../../../Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../Drivers/BSP/Components/M24SR -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Middlewares/ST/STM32_MetaDataManager -I../../../../../../../../Middlewares/ST/lib_NDEF/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/umqtt/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/iothub_client/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/c-utility/pal/generic -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/serializer/inc -I../../../../../../../../Middlewares/Third_Parties/Azure-IoT-SDK-C/parson -I../../../../../../../../Middlewares/Third_Parties/mbedtls/include -O2 -ffunction-sections -Wall -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-incompatible-pointer-types -Wno-format -fstack-usage -MMD -MP -MF"Middlewares/AzureIOT/xio.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

